### ISSUE TITLE
Add `vg` to sourcegen

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/PowerModelsDistribution.jl#124]
`PowerModels.check_voltage_setpoints` expects `"vg"` on generators, but current implementation of the sourcegen omits this field.

**Comment by ccoffrin** [comment]
I have been thinking about dropping this check from PowerModels.  Thus far, I have not seen any problem formulation that uses it.

@frederikgeth, what do you think?  This check trys to verify that the voltage setpoint in the given solution `vm` matches the _desired_ voltage setpoint of each generator `vg`.  Inpractice I don't find this information is every consistent in a given dataset.

**Comment by frederikgeth** [comment]
These parameters are indeed generally not consistent in data sets you find. 

The check is useful in the context of PQ/PV buses. 
- It is a property of a generator to have a voltage regulation control system operating w.r.t. a voltage setpoint
- but matpower actually applies voltage setpoints the bus level (PV buses).

A use case for me has been in the context of generator contingencies. If the data is consistent, you can trust that defining the voltage magnitude setpoint at the generators instead of the bus does not result  a trivial infeasibility. When you set a generator status to 0 as part of a contingency, its voltage setpoint constraint should also removed, thereby reverting the bus to a PQ bus (if there are no other generators at the bus). A PV bus without a generator connected to it often leads to very weird power flows (if at all feasible).

**Comment by ccoffrin** [comment]
The use case totally makes sense to me, but maybe we should only apply this consistency check in that context and not as part of the standard checks that are always performed when we read in data?

Also, in the case that two generators are attached to the same bus, is it reasonable for them to have different voltage setpoints?  Maybe that is a more general consistency check that we should be doing instead?

**Comment by frederikgeth** [comment]
I'm fine with removing the check between the buses and the generators and replacing it with a check of the setpoints amongst the generators for a specific bus (and/or DC lines).

I would be a bit sad about removing the check completely, as due to a lack of presolver, I find it is quite time consuming to figure out data inconsistencies through JuMP.

**Comment by ccoffrin** [comment]
When it comes to validity checks, the more the merrier.  My only sticking point is which to run always and which should be "opt-in".

**Comment by pseudocubic** [comment]
Discussion better on PowerModels.jl than here
