### ISSUE TITLE
normamps defined on lines instead of linecode

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/PowerModelsDistribution.jl#131]
It seems like defining `normamps` on lines directly has no effect on the `rate_a` property of the corresponding TPPM branch (idem for `emergamps` and `rate_b`)

**Comment by pseudocubic** [comment]
It turns out that in OpenDSS, where the linecode is defined matters significantly in the properties of the line, e.g. 

`new line.ohline bus1=sourcebus bus2=primary phases=3 normamps=10 linecode=556mcm` 

is different than 

`new line.ohline bus1=sourcebus bus2=primary phases=3 linecode=556mcm normamps=10`. 

In the first case, `normamps=10` will be overwritten by whatever is defined on the linecode, in the second case the linecode's `normamps` will be superseded by the one defined on the line. 

Note that even in the case where no `normamps` is explicitly given on a linecode, in the first case the default `normamps=400` will overwrite the `normamps=10` explicitly defined on the line.

Because we don't track the order that properties are defined, this functionality would be difficult to replicated. 

What I can do easily is throw a warning if overlapping properties are defined on both the line and linecode, and let the user know that one will overwrite the other. Currently we overwrite the line properties with the linecode properties, is this how we would prefer it, or would we prefer the other way?

**Comment by sanderclaeys** [comment]
I think the other way around makes more sense. 

The whole point of linecodes is to avoid duplication of properties. Wanting to refer to a linecode and overwriting certain properties at the line level, to me feels as what behaviour would be expected by the user. I do not see a use case for the other way around.

I suspect this is a quirk introduced by how OpenDSS parses properties in general. Some properties have a partial overlap with other properties, and if all of these are specified (which should not be allowed in the first place tbh), OpenDSS seems to apply them in the order they are specified.
