### ISSUE TITLE
parsing failure for 3-phase xfmrcodes

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/PowerModelsDistribution.jl#256]
The parser (at the `data-model` branch, I am a few commits behind atm) fails on the following input file (part of an IEEE feeder),
```
New Circuit.YYDTestCase
~ BasekV=69  Bus1=B1 Isc3=1000000  Isc1=1100000  ! near-infinite source

New XfmrCode.YYD3Phase phases=3 windings=3
~ conns=[wye  wye delta ]
~ kVs=[68.98758, 13.19823, 2.4]
~ kVAs=[15000 15000 5000]    ! 15 MVA 3-phase
~ XHL=7.5   XHT=36  XLT=28
~ %Rs = [0.11  0.11  0.275]

New Transformer.YYD  XfmrCode=YYD3Phase ppm=0
~ Buses=[B1.1.2.3.0 B3.1.2.3.0 B5.1.2.3]
```

It parses this as a 2-winding transformer instead; perhaps the phases argument is not merged in from the xfmrcode?

**Comment by sanderclaeys** [comment]
I think I managed to solve this as I was looking into parsing IEEE8500. There is a similar difficulty with line/linecode: default properties should not be be imported if a value is implied through the associated xfmrcode.

**Comment by sanderclaeys** [comment]
Also, `phases` should not be excluded for the `like` inclusion.

**Comment by pseudocubic** [comment]
it turns out `like` copies almost everything, but there are some exceptions, that as far as I can tell aren't documented, like `enabled`, the name of the object, `switch` on lines, etc.

I have changed the way `_apply_like!` works to address this.

I have also tested the example in the OP and it works for parsing into both data models.

I have also confirmed that 8500-node parses without error into both data models using my fixes

All tests now pass in data-model
