### ISSUE TITLE
Standardize make_multinetwork behavior

### ISSUE THREAD

**Issue by tasseff** [lanl-ansi/PowerModelsDistribution.jl#297]
I'm working quite frequently with multinetwork data and encountered an issue while playing with one of the sample files. Here's an example:

```julia
using PowerModelsDistribution
data = parse_file("test/data/opendss/case3_balanced.dss")
PowerModelsDistribution._IM.make_multinetwork(data, PowerModelsDistribution._pmd_eng_global_keys)
```

This breaks with

```julia
ERROR: KeyError: key "num_steps" not found
```

This will probably lead to a broader discussion, but:
1. To my knowledge, `num_steps` should be present in any InfrastructureModels network with a `time_series` block
2. I'd expect the above set of commands to create the corresponding multinetwork.
3. I noticed the function `_build_eng_multinetwork` is included in the package but am not sure how it differs from `IM.make_multinetwork` or why it was built.

**Comment by pseudocubic** [comment]
Where you're having the problem is that there are extra steps to go between the engineering model and a multinetwork mathematical model, you can't unfortunately use InfrastructureModels directly. The reason for this is that the `time_series` object in the engineering model is not the same as in InfrastructureModels, so in order to make multinetwork from an engineering model you should use 
```julia
mn_math_data = transform_data_model(data; build_multinetwork=true)
```

It is possible to build an engineering multinetwork data structure in the same format as InfrastructureModels expects it, but I didn't export those functions by default yet, in case there needed to be some breaking changes made in the near term. See https://github.com/lanl-ansi/PowerModelsDistribution.jl/blob/master/src/io/common.jl#L84-L87 for how you would do that.
