### ISSUE TITLE
[BUG] `add_start_vrvi!` on 13 Bus

### ISSUE THREAD

**Issue by felipemarkson** [lanl-ansi/PowerModelsDistribution.jl#393]
**Describe the bug**
I'm trying to use the `add_start_vrvi!` on IEEE 13 Bus multinetwork model and got a `DimensionMismatch` error in an internal function of the package.

_EDIT_: Even without the multinetwork model, the problem remains.

_EDIT_: Even removing the shapes and mode daily from the `.dss`, the problem remains.

I already checked the `.dss` file with the `OpenDSSDirect.jl` and everything is fine.

Is this bug releated to #389 ?

**Minimum Viable Example**
```julia
import PowerModelsDistribution
const PMD = PowerModelsDistribution

case_file = "13_bus_with_shape.dss"

model_dict = PMD.parse_file(case_file, transformations=[PMD.remove_all_bounds!])

# Transform to multinetwork
model_dict_mn = PMD.transform_data_model(model_dict, multinetwork=true)

# Initialize voltages
PMD.add_start_vrvi!(model_dict_mn)
```
See the **Additional context**.

**System Information (please complete the following information):**
 - OS: Manjaro Linux x86_64
 - Version: Kernel Linux 5.15.59-1-MANJARO 

**Additional context**
[bug.zip](https://github.com/lanl-ansi/PowerModelsDistribution.jl/files/9282922/bug.zip)

**Comment by pseudocubic** [comment]
I believe the problem is that `transform_data_model` performs Kron reduction by default, so you need to explicitly disable it, e.g., see the [Explicit Neutral Models](https://github.com/lanl-ansi/PowerModelsDistribution.jl/blob/main/examples/Explicit%20Neutral%20Models.jl#L144) Pluto Notebook in our documentation. 

Your code would change to:

```julia
model_dict_mn = PMD.transform_data_model(model_dict, multinetwork=true, kron_reduce=false, phase_project=false)
```

**Comment by felipemarkson** [comment]
I changed and the problem is solved.

But, when I tried to use `instantiate_mc_model`, I got the same problem with `IVRUPowerModel` and `build_mn_mc_opf`

```julia
pm = PMD.instantiate_mc_model(model_dict_mn, PMD.IVRUPowerModel, PMD.build_mn_mc_opf)
```

**Comment by pseudocubic** [comment]
To make sure I understand, in this case you are using data that is **not** kron reduced (`model_dict_mn`) with a formulation that expects kron-reduced data (`IVRUPowerModel`)?

If that is the case, it is a matter of data incompatibility, since the IVRU formulation does not know how to handle additional conductors (it expects <=3 conductors).

**Comment by felipemarkson** [comment]
Ok, I got it! Thanks!
But I don't see this information in the documentation, or am I missing something?

As a suggestion, an more explicit error will help a lot.

**Comment by pseudocubic** [comment]
It is probably missing from the documentation; the addition of explicit neutral formulations came much later, so we overlooked that the workflow you are attempting would be likely. 

I will look into whether there is a straightforward way to do some model-formulation compatibility checks, which has historically been one of the bigger pain points for new users.

**Comment by felipemarkson** [comment]
Maybe just a table that lists what model work with what formulation.

Thanks for your attention.

I am closing this issue.
