### ISSUE TITLE
[BUG] `parse_file` don't redirect when `.dss` is not in the parente file

### ISSUE THREAD

**Issue by felipemarkson** [lanl-ansi/PowerModelsDistribution.jl#396]
**Describe the bug**
Using the `parse_file` in a file that has a redirect which the next file doesn't end with `.dss` causes a `BoundsError`.

**Minimum Viable Example**

**DSS Files**

```
// redirect_test.dss
New   Load.Load_1   phases=3   conn=Wye   bus1=BUS_1   kw=0.1   kvar=0.03   model=1
```

```
// test.dss
Clear

new   circuit.test   bus1=SOURCEBUS   pu=1.0

New   Line.Line_1   bus1=SOURCEBUS   bus2=BUS_1

redirect redirect_test // Here is the problem! 

solve
```
**Julia Files**

```julia
import PowerModelsDistribution
const PMD = PowerModelsDistribution

case_file = "test.dss"

model_dict = PMD.parse_file(case_file)
```

**Expected behavior**
On OpenDSS and OpenDSSDirect.jl this example works well.

**Screenshots**
![image](https://user-images.githubusercontent.com/47871564/184969292-eb53b4e4-0e2d-4d3d-a6b5-24954cd3ad7e.png)

**System Information (please complete the following information):**
 - OS: Manjaro Linux x86_64
 - Version Kernel Linux 5.15.60-1-MANJARO

**Comment by felipemarkson** [comment]
Maybe, to fix this problem, the code below could be modified to check if the file ends with `.dss` and add the suffix if necessary.

https://github.com/lanl-ansi/PowerModelsDistribution.jl/blob/7a6b03eb0f96d0bcd3269b7d62ffda4d7ccaf4b0/src/io/dss/dss_parse.jl#L868-L877

@pseudocubic, If you are ok with that, I can create a PR.

**Comment by pseudocubic** [comment]
My feeling is that files should be specified explicitly/correctly in DSS redirect/compile commands, rather than attempt to add `.dss` to the end of what we interpret to be incomplete file names. The reason for this is that technically files don't need to end in `.dss` to be parsed by the parser, and doing this would break that functionality.

I think perhaps the better path here is to try to introduce a better error message for the user to indicate that either the file is missing or the filename is wrong.

**Comment by felipemarkson** [comment]
> I think perhaps the better path here is to try to introduce a better error message for the user to indicate that either the file is missing or the filename is wrong.

I agree
